### ISSUE TITLE
the building on travis-ci.org is ceased

### ISSUE THREAD

**Issue by shogo82148** [holidays-jp/generator#2]
It looks that the builds of this project are still on travis-ci.org
https://travis-ci.org/github/holidays-jp/generator/builds

However, since June 15th, 2021, the building on travis-ci.org is ceased.
ref. https://blog.travis-ci.com/2021-05-07-orgshutdown
https://github.com/holidays-jp/generator/blob/master/.travis.yml is not working.

**Comment by matsuoshi** [comment]
@shogo82148 ありがとうございます、GitHub Actions で build する方向で検討してみます

**Comment by matsuoshi** [comment]
@shogo82148 issue ありがとうございました、actions にて build できるようになったのでクローズさせていただきます
https://github.com/holidays-jp/api/actions
